# Generated by Django 4.2.6 on 2025-04-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0002_project_remove_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenvironment',
            name='leadership_support',
            field=models.CharField(max_length=100),
        ),
    ]
