# Generated by Django 4.2.6 on 2025-04-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0003_alter_projectenvironment_leadership_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenvironment',
            name='leadership_support',
            field=models.FloatField(),
        ),
    ]
