# Generated by Django 4.2.6 on 2025-04-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0004_alter_projectenvironment_leadership_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcomposition',
            name='avg_experience_level',
            field=models.CharField(max_length=100),
        ),
    ]
