# Generated by Django 4.2.6 on 2025-04-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0005_alter_teamcomposition_avg_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenvironment',
            name='leadership_support',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectenvironment',
            name='resource_availability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectenvironment',
            name='stakeholder_engagement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectenvironment',
            name='work_life_balance',
            field=models.CharField(max_length=100),
        ),
    ]
