# Generated by Django 4.2.6 on 2025-04-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0006_alter_projectenvironment_leadership_support_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalpractices',
            name='cicd_pipeline_usage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='technicalpractices',
            name='code_review_process',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='technicalpractices',
            name='devops_adoption',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='technicalpractices',
            name='security_practices',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='technicalpractices',
            name='technical_debt_level',
            field=models.CharField(max_length=100),
        ),
    ]
