# Generated by Django 4.2.6 on 2025-04-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0008_projectreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='planned_description',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
    ]
