# Generated by Django 4.2.6 on 2025-04-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0009_project_planned_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='planned_description',
            new_name='project_description',
        ),
    ]
